"""initial schema

Revision ID: c0c87bbe536a
Revises: 
Create Date: 2026-08-13 11:33:21.321414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c0c87bbe536a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('whatsapp_bsuid', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('role', sa.Enum('admin', 'user', name='userrole'), nullable=False),
    sa.Column('oauth_provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('oauth_subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_oauth_subject'), 'user', ['oauth_subject'], unique=False)
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=False)
    op.create_index(op.f('ix_user_whatsapp_bsuid'), 'user', ['whatsapp_bsuid'], unique=True)
    op.create_table('demand',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('location_text', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('administrative_area_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('administrative_area_level', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('address_text', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', name='recordstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demand_administrative_area_level'), 'demand', ['administrative_area_level'], unique=False)
    op.create_index(op.f('ix_demand_administrative_area_name'), 'demand', ['administrative_area_name'], unique=False)
    op.create_index(op.f('ix_demand_phone_number'), 'demand', ['phone_number'], unique=False)
    op.create_index(op.f('ix_demand_status'), 'demand', ['status'], unique=False)
    op.create_index(op.f('ix_demand_user_id'), 'demand', ['user_id'], unique=False)
    op.create_table('offer',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('location_text', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('administrative_area_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('administrative_area_level', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('address_text', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', name='recordstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_administrative_area_level'), 'offer', ['administrative_area_level'], unique=False)
    op.create_index(op.f('ix_offer_administrative_area_name'), 'offer', ['administrative_area_name'], unique=False)
    op.create_index(op.f('ix_offer_phone_number'), 'offer', ['phone_number'], unique=False)
    op.create_index(op.f('ix_offer_status'), 'offer', ['status'], unique=False)
    op.create_index(op.f('ix_offer_user_id'), 'offer', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offer_user_id'), table_name='offer')
    op.drop_index(op.f('ix_offer_status'), table_name='offer')
    op.drop_index(op.f('ix_offer_phone_number'), table_name='offer')
    op.drop_index(op.f('ix_offer_administrative_area_name'), table_name='offer')
    op.drop_index(op.f('ix_offer_administrative_area_level'), table_name='offer')
    op.drop_table('offer')
    op.drop_index(op.f('ix_demand_user_id'), table_name='demand')
    op.drop_index(op.f('ix_demand_status'), table_name='demand')
    op.drop_index(op.f('ix_demand_phone_number'), table_name='demand')
    op.drop_index(op.f('ix_demand_administrative_area_name'), table_name='demand')
    op.drop_index(op.f('ix_demand_administrative_area_level'), table_name='demand')
    op.drop_table('demand')
    op.drop_index(op.f('ix_user_whatsapp_bsuid'), table_name='user')
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.drop_index(op.f('ix_user_oauth_subject'), table_name='user')
    op.drop_table('user')
    op.execute('DROP TYPE IF EXISTS recordstatus')
    op.execute('DROP TYPE IF EXISTS userrole')
    # ### end Alembic commands ###
