"""add whatsapp conversations

Revision ID: d1cfd01d0f0b
Revises: d532dc48705b
Create Date: 2026-08-13 13:43:22.230974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd1cfd01d0f0b'
down_revision: Union[str, None] = 'd532dc48705b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_bsuid', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'abandoned', name='conversationstatus'), nullable=False),
    sa.Column('intent', sa.Enum('unknown', 'demand', 'offer', name='conversationintent'), nullable=False),
    sa.Column('current_step', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('last_message_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('llm_context_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('collected_data', sa.JSON(), nullable=True),
    sa.Column('message_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_intent'), 'conversation', ['intent'], unique=False)
    op.create_index(op.f('ix_conversation_status'), 'conversation', ['status'], unique=False)
    op.create_index(op.f('ix_conversation_user_id'), 'conversation', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversation_whatsapp_bsuid'), 'conversation', ['whatsapp_bsuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_whatsapp_bsuid'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_user_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_status'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_intent'), table_name='conversation')
    op.drop_table('conversation')
    op.execute('DROP TYPE IF EXISTS conversationintent')
    op.execute('DROP TYPE IF EXISTS conversationstatus')
    # ### end Alembic commands ###
