"""normalize tags

Revision ID: d532dc48705b
Revises: f37a558a2bab
Create Date: 2026-08-13 12:48:30.115980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd532dc48705b'
down_revision: Union[str, None] = 'f37a558a2bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.create_table('demandtag',
    sa.Column('demand_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['demand.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('demand_id', 'tag_id'),
    sa.UniqueConstraint('demand_id', 'tag_id')
    )
    op.create_table('offertag',
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('offer_id', 'tag_id'),
    sa.UniqueConstraint('offer_id', 'tag_id')
    )
    op.execute("""
        INSERT INTO tag (name, created_at, updated_at)
        SELECT DISTINCT normalized.name, now(), now()
        FROM (
            SELECT lower(trim(value::text, '"')) AS name
            FROM offer, json_array_elements(offer.tags) AS value
            WHERE offer.tags IS NOT NULL
            UNION
            SELECT lower(trim(value::text, '"')) AS name
            FROM demand, json_array_elements(demand.tags) AS value
            WHERE demand.tags IS NOT NULL
        ) AS normalized
        WHERE normalized.name != ''
        ON CONFLICT (name) DO NOTHING
    """)
    op.execute("""
        INSERT INTO offertag (offer_id, tag_id)
        SELECT offer.id, tag.id
        FROM offer
        JOIN LATERAL json_array_elements(offer.tags) AS value ON offer.tags IS NOT NULL
        JOIN tag ON tag.name = lower(trim(value::text, '"'))
        ON CONFLICT DO NOTHING
    """)
    op.execute("""
        INSERT INTO demandtag (demand_id, tag_id)
        SELECT demand.id, tag.id
        FROM demand
        JOIN LATERAL json_array_elements(demand.tags) AS value ON demand.tags IS NOT NULL
        JOIN tag ON tag.name = lower(trim(value::text, '"'))
        ON CONFLICT DO NOTHING
    """)
    op.drop_column('demand', 'tags')
    op.drop_column('offer', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('demand', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('offertag')
    op.drop_table('demandtag')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
