"""add admin authentication

Revision ID: d60aa0521927
Revises: c0c87bbe536a
Create Date: 2026-08-13 11:48:31.853453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd60aa0521927'
down_revision: Union[str, None] = 'c0c87bbe536a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauthidentity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject')
    )
    op.create_index(op.f('ix_oauthidentity_provider'), 'oauthidentity', ['provider'], unique=False)
    op.create_index(op.f('ix_oauthidentity_subject'), 'oauthidentity', ['subject'], unique=False)
    op.create_index(op.f('ix_oauthidentity_user_id'), 'oauthidentity', ['user_id'], unique=False)
    op.add_column('user', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('user', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'username')
    op.drop_index(op.f('ix_oauthidentity_user_id'), table_name='oauthidentity')
    op.drop_index(op.f('ix_oauthidentity_subject'), table_name='oauthidentity')
    op.drop_index(op.f('ix_oauthidentity_provider'), table_name='oauthidentity')
    op.drop_table('oauthidentity')
    # ### end Alembic commands ###
