"""use oauth provider enum

Revision ID: f37a558a2bab
Revises: d60aa0521927
Create Date: 2026-08-13 12:13:30.881270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f37a558a2bab'
down_revision: Union[str, None] = 'd60aa0521927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    oauthprovider = sa.Enum('local', 'google', 'meta', name='oauthprovider')
    oauthprovider.create(op.get_bind(), checkfirst=True)
    op.alter_column('oauthidentity', 'provider',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('local', 'google', 'meta', name='oauthprovider'),
               existing_nullable=False,
               postgresql_using='provider::oauthprovider')
    op.alter_column('user', 'oauth_provider',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('local', 'google', 'meta', name='oauthprovider'),
               existing_nullable=True,
               postgresql_using='oauth_provider::oauthprovider')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'oauth_provider',
               existing_type=sa.Enum('local', 'google', 'meta', name='oauthprovider'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               postgresql_using='oauth_provider::text')
    op.alter_column('oauthidentity', 'provider',
               existing_type=sa.Enum('local', 'google', 'meta', name='oauthprovider'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using='provider::text')
    sa.Enum('local', 'google', 'meta', name='oauthprovider').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
